// Authored suggestions grouped by theme, not generated from interchangeable templates.
// IDs use group + position. Append only: keep existing positions stable for saved diaries.
const groups = [
  {
    "prefix": "everyday-discovery",
    "category": "Be present",
    "duration": "5 min",
    "icon": "❋",
    "company": "solo",
    "texts": [
      "Find a reflection hiding in an ordinary object",
      "Notice how a familiar object changes under different light",
      "Follow one repeating shape across the room with your eyes",
      "Compare the shadows cast by two nearby objects",
      "Find something handmade and notice a maker's small decisions",
      "Choose a small object and observe it from underneath",
      "Notice which colors sit next to each other on a bookshelf",
      "Look for a spiral in something you already own",
      "Find an object that has become smoother with use",
      "Notice the longest uninterrupted line in your surroundings",
      "Observe how fabric folds when you set it down",
      "Look for a tiny detail on a favorite piece of clothing",
      "Notice how a room sounds with the door open and closed",
      "Hold a smooth stone and notice its weight",
      "Find an everyday object that fits neatly in your palm",
      "Notice the shapes in the spaces between objects",
      "Look for two objects with unexpectedly similar textures",
      "Study the lettering on a package you already have",
      "Follow the movement of a curtain for a moment",
      "Watch a drop of water travel down a glass",
      "Notice the quiet pause after a familiar sound ends",
      "Find an object that catches light at its edges",
      "Compare the sound of gently tapping two safe surfaces",
      "Look for a color that appears only once nearby",
      "Study the stitching on a bag or cushion",
      "Look at the same view through a small paper frame",
      "Notice the different sounds of turning a book's pages",
      "Compare the weight of two familiar objects",
      "Look for a tiny asymmetry in something you like",
      "Notice the grain of a wooden surface",
      "Watch a spoon's reflection change as you turn it",
      "Find an object whose shape suggests an animal",
      "Look for something repaired rather than replaced",
      "Notice where natural light feels softest in your room",
      "Examine the edge of a leaf without removing it",
      "Notice the pattern left by a wet cup on a coaster",
      "Compare a fabric's appearance up close and from farther away",
      "Find a pleasing pair of colors in your surroundings",
      "Watch water ripple gently in a bowl",
      "Notice how your handwriting looks when you write slowly",
      "Look for a detail in your shoes you have never noticed",
      "Notice how a favorite object has aged",
      "Follow the outline of a chair with your eyes",
      "Find a surface that looks different from how it feels",
      "Observe the tiny bubbles in a glass of water",
      "Compare how two different papers sound when folded",
      "Look for a shape echoed in both furniture and nature",
      "Study a small corner of a familiar picture",
      "Notice where the room's colors become warmer or cooler",
      "Find a comforting detail in an otherwise ordinary space",
      "Choose an everyday sound as the soundtrack to a short pause"
    ]
  },
  {
    "prefix": "small-making",
    "category": "Create",
    "duration": "10 min",
    "icon": "✎",
    "company": "solo",
    "texts": [
      "Draw an imaginary house for a very small animal",
      "Make a paper crown for a favorite object",
      "Write a tiny advertisement for a perfectly ordinary spoon",
      "Design a ticket to an imaginary destination",
      "Draw a garden using only circles and curved lines",
      "Make a miniature flag for your desk",
      "Write a recipe for a fictional kind of weather",
      "Draw a portrait of your bag as a character",
      "Fold scrap paper into a little standing sign",
      "Design a postage stamp for your neighborhood",
      "Write a friendly message in decorative lettering",
      "Draw a city skyline using objects on your table as inspiration",
      "Create a simple comic about a sock's adventure",
      "Make a small paper envelope for a future note",
      "Draw a flower using your less familiar hand",
      "Design a logo for an imaginary bookshop",
      "Arrange torn paper into a tiny landscape",
      "Write a three-sentence fairytale about a lost button",
      "Draw a menu for a café run by animals",
      "Make a paper chain with a few scraps",
      "Design a medal for an ordinary accomplishment",
      "Sketch a chair as if it belonged in a palace",
      "Write a short description of an imaginary holiday",
      "Draw a map of your room as a treasure island",
      "Make a tiny paper sign for your favorite snack",
      "Create a pattern inspired by raindrops",
      "Draw the same object using only triangles",
      "Write a friendly letter from the perspective of your houseplant",
      "Design a cover for a playlist you enjoy",
      "Make a small paper boat and display it on a shelf",
      "Draw a creature made from three household objects",
      "Write a two-person dialogue between a mug and a kettle",
      "Decorate the corner of a notebook page",
      "Design a whimsical door for a fairy-sized visitor",
      "Draw an imaginary bicycle with an unusual feature",
      "Make a constellation by connecting scattered pencil dots",
      "Write a tiny travel guide to your sofa",
      "Sketch a fruit as a tiny planet",
      "Create an abstract picture using only two colors",
      "Design a cheerful label for a storage box",
      "Draw a robot whose only job is spreading kindness",
      "Write a miniature museum label for a keepsake",
      "Make a simple paper flower from a scrap",
      "Draw a fictional shopfront for something impossible",
      "Create a border of leaves around a blank note",
      "Write a silly instruction manual for taking a nap",
      "Draw a favorite meal as a collection of simple shapes",
      "Design a tiny calendar illustration for today's date",
      "Make a paper puppet with a friendly expression",
      "Draw a bridge between two imaginary worlds",
      "Write the first sentence of a story you might enjoy"
    ]
  },
  {
    "prefix": "restful-pauses",
    "category": "Slow down",
    "duration": "5 min",
    "icon": "☾",
    "company": "solo",
    "texts": [
      "Place your phone face down while you enjoy a quiet pause",
      "Sit beside a lamp instead of under a bright overhead light",
      "Listen to the final notes of a song fade completely",
      "Let yourself stop reading at a comfortable point",
      "Rest against a supportive cushion with nothing to finish",
      "Leave a short gap between two everyday activities",
      "Move away from your work surface for a quiet drink",
      "Sit with a favorite blanket across your lap",
      "Watch a short stretch of sky without taking a picture",
      "Choose silence for one familiar household activity",
      "Let a pleasant thought stay without turning it into a plan",
      "Take off your headphones and notice the room again",
      "Hold a warm mug comfortably in both hands",
      "Put your unfinished project somewhere safe for a break",
      "Switch to a softer screen brightness if that feels comfortable",
      "Sit near an open doorway when the weather is pleasant",
      "Fold a blanket slowly, enjoying the simple movement",
      "Let the next song play without checking its length",
      "Set aside a book you are not enjoying without guilt",
      "Rest your forearms on a comfortable surface",
      "Spend a brief pause looking farther away from your screen",
      "Choose an unhurried route through your next small chore",
      "Sit somewhere you usually only pass through",
      "Put away a timer for an activity that does not need one",
      "Notice that a break does not need to be earned",
      "Rest with a comforting familiar sound in the background",
      "Read a favorite line twice, leaving a pause between readings",
      "Let yourself finish a drink before opening another tab",
      "Arrange your pillow before taking a short rest",
      "Choose a quieter corner for your next pause",
      "Watch a familiar room settle after you stop moving",
      "Slowly trace a simple shape on paper",
      "Take a break between replying to messages",
      "Let yourself listen without planning what to do next",
      "Enjoy a few moments before turning on a screen",
      "Place a book within reach and decide later whether to read",
      "Sit comfortably while waiting for something ordinary",
      "Wrap your hands loosely in a soft towel for a moment",
      "Allow an ordinary activity to take its natural time",
      "Choose a gentler notification volume if the current one startles you",
      "Step away from an unfinished list for one song",
      "Close your laptop lid for a short intentional pause",
      "Rest your gaze on a single calm color",
      "Put a cushion under your feet if that feels comfortable",
      "Enjoy a quiet transition after arriving home",
      "Pause in a comfortable spot before starting your evening",
      "Choose a familiar album and let someone else set the pace",
      "Take a little time to do absolutely nothing useful",
      "Let a short break end when you feel ready",
      "Sit where you can enjoy both light and shade",
      "Leave yourself a small pocket of unscheduled time today"
    ]
  },
  {
    "prefix": "curious-detours",
    "category": "Get inspired",
    "duration": "10 min",
    "icon": "✦",
    "company": "solo",
    "texts": [
      "Learn why a familiar street has its name",
      "Look up how paper is recycled",
      "Discover an unusual musical instrument and hear its sound",
      "Read about the history of a familiar board game",
      "Learn how a zipper works",
      "Explore a photograph from a local history collection",
      "Find out how a favorite fruit grows",
      "Read about the design of an everyday chair",
      "Discover a traditional craft from a place you know little about",
      "Learn why soap makes bubbles",
      "Look up the story behind a local landmark",
      "Read a short explanation of how a rainbow forms",
      "Find a public-domain illustration that catches your eye",
      "Learn about the process of making pottery",
      "Explore a map of a place from long ago",
      "Read about an invention created by accident",
      "Find out how a mechanical music box works",
      "Learn a new word for a color",
      "Read about the life cycle of a butterfly",
      "Explore an architectural detail on a building you like",
      "Listen to a short recording of an unfamiliar instrument",
      "Learn how a compass finds north",
      "Read about a small museum you have never visited",
      "Find out how woven fabric is made",
      "Explore the story of a familiar typeface",
      "Learn about an animal's unusual way of communicating",
      "Look up how stained glass is made",
      "Read a short account of an ocean discovery",
      "Learn why leaves change color",
      "Explore a library's collection of old posters",
      "Read about the history of a familiar dessert",
      "Discover a bridge with an interesting design",
      "Learn how a seed travels away from its plant",
      "Find out what makes different bells sound different",
      "Read about an artist who worked with everyday materials",
      "Explore the origin of a common household tool",
      "Learn about a traditional form of storytelling",
      "Find out how a kaleidoscope makes patterns",
      "Read about a garden designed for a small space",
      "Discover a short film made with stop-motion animation",
      "Learn why the moon sometimes appears during daytime",
      "Look up how books were bound before modern machines",
      "Read about an unusual adaptation in a desert plant",
      "Explore a piece of public art near your area online",
      "Learn how an hourglass measures time",
      "Find a simple explanation of how a bicycle gear works",
      "Read about a craftsperson who repairs old objects",
      "Learn about a food-growing tradition in another region",
      "Explore the pattern of a traditional textile",
      "Find out how a record player produces sound",
      "Read about a creative use for a material usually discarded"
    ]
  },
  {
    "prefix": "playful-minutes",
    "category": "Little joy",
    "duration": "5 min",
    "icon": "✳",
    "company": "solo",
    "texts": [
      "Invent a secret identity for your favorite mug",
      "Give three nearby objects imaginary job titles",
      "Find five words hidden inside a longer word",
      "Balance a small stack of clean, unbreakable containers",
      "Make a tiny obstacle course for your fingertip on a table",
      "Invent a superhero whose power is unusually ordinary",
      "Arrange your pens from shortest to longest",
      "Try writing your name as a mirror image",
      "Make up a cheerful sound for finishing a small chore",
      "Turn a scrap of paper into a tiny basketball",
      "Find an animal shape in a crumpled piece of paper",
      "Invent a new rule for a familiar solo word game",
      "Give your room an imaginary movie title",
      "Try drawing a star without lifting your pencil",
      "Make a tiny parade of objects already on your desk",
      "Choose a theme song for an imaginary entrance",
      "Create a word ladder from one short word to another",
      "Invent a friendly monster that eats missing socks",
      "Build the smallest possible tower from objects at hand",
      "Make a silly sentence using five nearby objects",
      "Try describing your day using only food names",
      "Imagine what your furniture would say at a meeting",
      "Give a familiar object an unnecessarily grand title",
      "Make a miniature maze on scrap paper",
      "Find three objects that could form a pretend band",
      "Invent a handshake using only your own fingers",
      "Make up a mascot for a favorite household chore",
      "Create a tiny mystery with an ordinary object as the clue",
      "Try a round of finger drumming on your knees",
      "Draw a face on scrap paper and give it an absurdly long name",
      "Invent a new flavor of imaginary ice cream",
      "Make a word from the first letters of objects around you",
      "Think of five gentle uses for an imaginary magic wand",
      "Pretend your room is a museum and choose its star exhibit",
      "Arrange a few coins into a picture without spending them",
      "Invent a creature that would fit in a matchbox",
      "Try saying a gentle tongue twister at your own pace",
      "Draw a little racecourse and trace it with your finger",
      "Choose an imaginary award for your most reliable object",
      "Create a tiny treasure hunt for yourself using three clues",
      "Make a playful nickname for the current weather",
      "Invent a machine that solves a wonderfully small problem",
      "Turn the letters of your name into little drawings",
      "Give an ordinary snack a fancy restaurant name",
      "Make a tiny paper hat for a pen",
      "Imagine a conversation between two objects on your shelf",
      "Create a nonsense word and decide what it means",
      "Try making a simple rhythm with two different surfaces",
      "Invent a friendly password for an imaginary treehouse",
      "Draw a map of a place that exists only in a dream",
      "Choose an imaginary adventure for your next cup of tea"
    ]
  },
  {
    "prefix": "gentle-care",
    "category": "Self kindness",
    "duration": "5 min",
    "icon": "♡",
    "company": "solo",
    "texts": [
      "Place a useful item where your future self can find it easily",
      "Choose the most comfortable cup for your next drink",
      "Replace a scratchy layer with something softer if you can",
      "Let yourself use a shortcut for a nonessential chore",
      "Put a small reminder of a happy place near your workspace",
      "Turn down a background sound you no longer enjoy",
      "Clear one item from the chair where you want to rest",
      "Set a comforting book beside your bed",
      "Give yourself credit for asking for help before",
      "Choose a task you can leave imperfect today",
      "Move something you use often closer to hand",
      "Untangle one cable that keeps getting in your way",
      "Set out a comfortable layer for later",
      "Put a pleasant object beside a practical one",
      "Refresh the water in a bottle you use regularly",
      "Let yourself change your mind about a small plan",
      "Make your next break a little easier to take",
      "Choose a seat based on comfort rather than habit",
      "Replace a harsh reminder with kinder wording",
      "Put a spare tissue or napkin somewhere useful",
      "Pick a familiar activity that asks little of you",
      "Move a distracting item out of your immediate view",
      "Give yourself permission to enjoy something without becoming good at it",
      "Choose a small convenience without feeling guilty about it",
      "Leave a kind note where you tend to feel rushed",
      "Set a manageable endpoint for a task that could go on forever",
      "Put your favorite everyday item into use instead of saving it",
      "Let yourself skip a nonessential update or notification",
      "Create a little landing spot for things you carry home",
      "Choose clothing for how it feels today",
      "Make a simple backup plan for a tiring evening",
      "Move a drink away from electronics so you can relax",
      "Give yourself a little extra time for one transition",
      "Let an ordinary meal be enough today",
      "Put a comforting photo somewhere you can easily revisit it",
      "Choose one small boundary that makes your afternoon easier",
      "Set down something you have been carrying unnecessarily",
      "Acknowledge an effort nobody else saw",
      "Give yourself permission to stop an activity you are not enjoying",
      "Make your resting place ready before you need it",
      "Keep a small useful item in the pocket you actually use",
      "Choose a familiar route if novelty feels tiring today",
      "Let yourself accept a small kindness without explaining it away",
      "Put a reminder of a personal interest where you can see it",
      "Choose a gentle alternative to one demanding plan",
      "Make the next necessary step smaller than you first imagined",
      "Set aside something that keeps snagging or bothering you",
      "Allow yourself to enjoy a favorite thing without sharing it online",
      "Notice one way you have already cared for yourself today",
      "Pick a low-effort comfort you can enjoy right now",
      "Say a quiet thank-you to yourself for trying"
    ]
  },
  {
    "prefix": "nearby-nature",
    "category": "Fresh air",
    "duration": "10 min",
    "icon": "☀",
    "company": "solo",
    "texts": [
      "Find a tree whose branches make an interesting outline",
      "Notice how the same path looks in a different kind of light",
      "Watch a small patch of grass move in the breeze",
      "Look for a seed pod without disturbing it",
      "Listen for the difference between wind in leaves and wind nearby",
      "Observe a bird from a respectful distance",
      "Look for a plant growing in an unexpected place",
      "Notice the shapes of stones along a safe path",
      "Find a view framed by two trees",
      "Watch the reflection of the sky in a puddle",
      "Notice which outdoor colors are brightest after rain",
      "Look for a fallen leaf with an unusual pattern",
      "Compare the shapes of two nearby tree canopies",
      "Watch a distant cloud slowly change shape",
      "Notice a tiny patch of moss without touching it",
      "Find a place where sunlight makes a pattern on the ground",
      "Look at a familiar outdoor scene from a seated position",
      "Observe how a climbing plant follows its support",
      "Look for a natural arch made by branches",
      "Notice where birds choose to pause nearby",
      "Find a place outside where you can comfortably stand still",
      "Look for signs of new growth on a familiar plant",
      "Notice how shadows show the shape of leaves",
      "Watch a small insect from a respectful distance",
      "Find two outdoor textures that contrast with each other",
      "Look for a tree with an interesting bend in its trunk",
      "Notice how the air feels in a shaded spot",
      "Watch a distant flag or branch show the wind's direction",
      "Observe how water gathers on a leaf after rain",
      "Find a safe place to enjoy the smell of fresh rain",
      "Look for a small seasonal change near your doorway",
      "Notice the border between a garden and a path",
      "Watch ripples on a pond from a safe distance",
      "Look for a plant with a pleasing arrangement of leaves",
      "Notice the sound of your steps on a familiar safe surface",
      "Observe the different greens in one small outdoor area",
      "Find an outdoor view you would like to sketch later",
      "Look for a bird-shaped cloud without needing to photograph it",
      "Notice how a tree frames a piece of sky",
      "Sit near a garden and listen without naming every sound",
      "Look for a fallen twig with a characterful shape",
      "Notice which flowers are open at this time of day",
      "Watch the movement of tall grass from a safe path",
      "Find a natural pattern that repeats at different sizes",
      "Observe how a plant leans toward available light",
      "Look for a gentle curve in an outdoor path",
      "Notice the sound of leaves beneath a light breeze",
      "Find a little spot of green visible from indoors",
      "Watch the space between two passing clouds widen",
      "Look for a peaceful outdoor detail at your own pace",
      "Return your attention to one natural thing when your mind wanders"
    ]
  },
  {
    "prefix": "easy-conversations",
    "category": "Connect",
    "duration": "10 min",
    "icon": "♡",
    "company": "together",
    "texts": [
      "Trade descriptions of your ideal tiny reading nook with someone",
      "Ask a friend which ordinary sound they find comforting",
      "Take turns naming places you would revisit just for the atmosphere",
      "Compare the little rituals you each enjoy before a day off",
      "Ask someone what they liked making as a child",
      "Trade stories about a surprisingly good ordinary day",
      "Describe your dream neighborhood café to each other",
      "Ask a friend which fictional place they would visit for an afternoon",
      "Compare the objects you both keep for sentimental reasons",
      "Take turns describing a view you remember fondly",
      "Ask someone which small invention makes their life easier",
      "Talk about a hobby you would each try without needing to excel",
      "Trade memories of a favorite school lunch or snack",
      "Compare the kinds of weather that make you want to slow down",
      "Ask someone about a kind teacher or mentor they remember",
      "Take turns describing a room that felt welcoming",
      "Trade stories about an amusing misunderstanding you can both laugh about",
      "Compare what you each notice first in a new place",
      "Ask a friend about a book cover they love",
      "Describe an imaginary shop you would enjoy running together",
      "Trade memories of a neighborhood you once knew well",
      "Ask someone about a little tradition they would like to keep",
      "Compare your favorite ways to spend a free half-hour",
      "Take turns sharing an unexpectedly useful piece of advice",
      "Ask a friend which everyday skill they enjoy using",
      "Describe a perfect picnic location to each other",
      "Trade stories about something you learned from a grandparent or older friend",
      "Compare your favorite kinds of quiet company",
      "Ask someone which childhood game they would still enjoy",
      "Take turns describing an object that has traveled with you",
      "Talk about a small discovery that recently made you smile",
      "Ask a friend what they would put in a miniature museum",
      "Compare the sounds you associate with home",
      "Trade descriptions of a favorite window view",
      "Ask someone which handmade gift they remember most clearly",
      "Take turns naming a place you would show a visitor",
      "Compare your favorite details in a familiar shared space",
      "Ask a friend about an animal encounter that delighted them",
      "Imagine a gentle holiday you could invent together",
      "Trade stories about a time a plan changed in a pleasant way",
      "Ask someone which everyday task they secretly enjoy",
      "Compare your favorite beginnings to a relaxed weekend",
      "Take turns describing a color through objects rather than its name",
      "Ask a friend what they would grow in a tiny garden",
      "Talk about a simple pleasure that costs nothing",
      "Compare the kinds of stories you return to for comfort",
      "Ask someone about a useful habit they learned from another person",
      "Trade memories of a favorite local shop",
      "Describe a dream train journey to each other",
      "Ask a friend which familiar place they see differently now",
      "Take turns sharing something small you are curious about lately"
    ]
  },
  {
    "prefix": "make-together",
    "category": "Create",
    "duration": "15 min",
    "icon": "✎",
    "company": "together",
    "texts": [
      "Draw one imaginary creature together, taking turns adding features",
      "Build a small paper town with someone",
      "Make a two-person comic, alternating panels",
      "Create a shared postcard from an imaginary holiday",
      "Design a friendly mascot together for your room or group",
      "Take turns adding one line to an abstract drawing",
      "Make a tiny paper garden with a friend",
      "Write a short story together using three objects nearby",
      "Design matching bookmarks with different patterns",
      "Create a shared collage from spare paper",
      "Draw portraits of each other using only simple shapes",
      "Make an illustrated menu for an imaginary café together",
      "Invent a board game together on one sheet of paper",
      "Decorate a paper frame for a shared memory",
      "Draw a map of a made-up neighborhood together",
      "Make little paper flags for each other's interests",
      "Write a gentle comedy scene together in six lines",
      "Build a tabletop sculpture together from unbreakable objects",
      "Design a logo for an imaginary club you would both join",
      "Create a picture together using only torn paper shapes",
      "Take turns inventing captions for a harmless doodle",
      "Make a tiny paper theater and two characters together",
      "Design a shared invitation to an imaginary celebration",
      "Write a silly weather forecast together",
      "Draw a garden together where every plant has an impossible feature",
      "Make a two-color pattern by alternating pencil marks",
      "Create a short poem together, one word at a time",
      "Design a pretend currency for a world built on kindness",
      "Make a paper garland together with materials already available",
      "Draw the same scene from each other's description",
      "Create a tiny illustrated guide to a favorite shared place",
      "Write a friendly dialogue between two fictional animals together",
      "Design a cozy room together without a budget limit",
      "Make simple paper badges for each other's strengths",
      "Create a story together that begins with an unexpected parcel",
      "Draw a collaborative maze and try tracing it",
      "Invent packaging together for an imaginary delightful product",
      "Make a small poster celebrating an ordinary shared pleasure",
      "Design a treehouse together with one unusual room each",
      "Create a comic about two objects meeting for the first time",
      "Write an imaginary museum tour together",
      "Make a folded-paper mini book and each fill half",
      "Design a shared playlist cover on scrap paper",
      "Draw a fantastical vehicle together, alternating useful and silly parts",
      "Create a pattern inspired by a place you both know",
      "Make a pretend travel brochure for your living room together",
      "Write a cheerful jingle together for an ordinary object",
      "Draw a shared alphabet made of tiny pictures",
      "Create a paper creature and take turns giving it adventures",
      "Design a tiny stage set together for a favorite story",
      "Make a simple thank-you card together for someone you both appreciate"
    ]
  },
  {
    "prefix": "little-games",
    "category": "Play together",
    "duration": "10 min",
    "icon": "✳",
    "company": "together",
    "texts": [
      "Play a round of twenty questions about an everyday object",
      "Take turns drawing animals for the other person to guess",
      "Play a gentle word-association game with a friend",
      "Invent a story together using alternating sentences",
      "Challenge each other to name five things of one color",
      "Play a round of charades using favorite hobbies",
      "Take turns humming a familiar tune for the other to guess",
      "Play a quick round of tic-tac-toe on scrap paper",
      "Make up riddles about objects in the room for each other",
      "Play an alphabet game using things that bring comfort",
      "Take turns naming imaginary shops on a made-up street",
      "Challenge each other to draw a bicycle from memory",
      "Play a counting game where multiples of five become funny words",
      "Guess an object from three clues given by a friend",
      "Build little towers and compare their personalities rather than their height",
      "Play a round of charades using household chores",
      "Take turns finishing the sentence of a nonsense story",
      "Challenge each other to find a word inside a longer word",
      "Play a memory game with five objects on a tray",
      "Invent gentle tongue twisters and try them together",
      "Guess which nearby object a friend has described as a person",
      "Play a drawing game using your less familiar hands",
      "Take turns naming something that rhymes with a chosen word",
      "Create a three-clue treasure hunt for each other in one room",
      "Play a guessing game using only yes-or-no questions about food",
      "Challenge each other to draw a cat using five lines",
      "Play a round of pretend shopkeeper with imaginary products",
      "Take turns making a simple hand rhythm for the other to copy",
      "Guess a favorite story from a deliberately vague description",
      "Make a paper maze for each other to solve",
      "Play an animal alphabet game together without keeping score",
      "Challenge each other to describe a spoon without naming its use",
      "Take turns acting out an imaginary robot's daily routine",
      "Play a round of categories using only things found outdoors",
      "Invent two believable facts about a fictional creature together",
      "Guess an object by listening to a gentle tapping sound",
      "Play a short game of dots and boxes on paper",
      "Take turns giving silly but kind awards to nearby objects",
      "Challenge each other to create the friendliest imaginary monster",
      "Play a naming game for an imaginary litter of kittens",
      "Guess a season from three details chosen by a friend",
      "Take turns drawing a shape that the other turns into something",
      "Play a story game where every sentence includes a color",
      "Challenge each other to think of unusual uses for a cardboard box",
      "Play a round of silent charades using weather",
      "Guess an everyday object from a close-up photo taken by a friend",
      "Take turns inventing a word and guessing what it might mean",
      "Play a cooperative alphabet game about a dream holiday",
      "Challenge each other to make a smiling face from desk objects",
      "Play a tiny mystery game with one ordinary object as the answer",
      "Invent a short game together where nobody needs to win"
    ]
  },
  {
    "prefix": "shared-sound",
    "category": "Music together",
    "duration": "10 min",
    "icon": "♫",
    "company": "together",
    "texts": [
      "Listen to one unfamiliar song together and compare first impressions",
      "Take turns choosing a song for a pretend road trip",
      "Make a two-song playlist that moves from busy to calm",
      "Listen for the bass line in a song together",
      "Choose a song each for an imaginary rainy-day café",
      "Tap out a simple rhythm together on a safe surface",
      "Share a song you associate with a particular place",
      "Listen to a live version of a song you both know",
      "Choose music together for a fictional movie scene",
      "Take turns introducing a song without naming the artist",
      "Listen to an instrumental piece and imagine its setting together",
      "Build a tiny playlist around one shared color",
      "Sing a familiar chorus together if you both feel like it",
      "Compare the opening moments of two songs you like",
      "Pick a song together that sounds like early morning",
      "Listen for a background instrument you had not noticed before",
      "Create a gentle call-and-response rhythm with a friend",
      "Choose one song each that would fit a peaceful train ride",
      "Talk about the cover art while listening to an album track",
      "Listen to a short piece from a genre new to both of you",
      "Make a three-song soundtrack for an imaginary garden party",
      "Take turns sharing a song someone introduced you to",
      "Listen to a favorite track together without talking over it",
      "Choose a song each for a fictional character's entrance",
      "Try tapping the same beat with different everyday objects",
      "Compare how an acoustic and recorded version of a song feel",
      "Pick music together for a slow craft session",
      "Listen to a short film soundtrack and invent a scene for it",
      "Share a song that reminds you of a harmless funny memory",
      "Make a tiny playlist with a friend using only gentle titles",
      "Take turns choosing a song from a different decade",
      "Listen for a repeated melody in a piece together",
      "Create a short rhythm using claps and finger taps together",
      "Choose music together for an imaginary bookstore",
      "Share a favorite song lyric in your own words and discuss its mood",
      "Listen to a song with a friend and each notice a different instrument",
      "Pick a cheerful song together for a little stretch or sway",
      "Make a two-song playlist that contrasts sunshine and rain",
      "Trade stories about the first music you chose for yourselves",
      "Listen to a short piano piece together and imagine a landscape",
      "Choose a song each to accompany making a warm drink",
      "Try quietly humming two different notes together",
      "Listen to a familiar song and count a repeating sound together",
      "Build a playlist title together before choosing its first song",
      "Share a song whose arrangement you find surprising",
      "Choose music together that would suit a tiny seaside café",
      "Listen to a short percussion piece and notice its patterns together",
      "Take turns choosing a musical instrument you would enjoy trying",
      "Make a gentle rhythm that represents walking through an imaginary city",
      "Listen to a song together and give its mood a playful name",
      "End a shared music break with a song you both find comforting"
    ]
  },
  {
    "prefix": "outside-company",
    "category": "Explore together",
    "duration": "15 min",
    "icon": "☀",
    "company": "together",
    "texts": [
      "Take a short walk together and each point out one overlooked detail",
      "Sit outside with someone and compare the sounds you notice",
      "Find two different leaf shapes together without picking them",
      "Choose a nearby bench and share a quiet pause",
      "Look for interesting doorway colors together on a familiar street",
      "Watch clouds together and describe different shapes you see",
      "Visit a nearby public garden together if accessible",
      "Take turns choosing the next turn on a short familiar route",
      "Find a tree together that would make a good story character",
      "Look for repeating patterns on buildings together",
      "Enjoy a shaded outdoor drink with someone",
      "Walk together toward a familiar landmark at an unhurried pace",
      "Look for natural shapes that resemble letters together",
      "Compare the reflections in two safe nearby puddles",
      "Listen for birds together without needing to identify them",
      "Find a little outdoor view you would both like to draw",
      "Notice three signs of the season together",
      "Take a short photo walk together without photographing strangers",
      "Look for small details on a shared familiar route",
      "Sit near a tree and each describe its silhouette",
      "Explore a nearby public path together within your comfort level",
      "Find two outdoor colors that look good beside each other",
      "Watch the breeze move different plants together",
      "Visit a familiar corner at a different time of day together",
      "Look for interesting roof shapes together",
      "Take turns naming something beautiful along a short route",
      "Share a quiet moment looking at an open patch of sky",
      "Find a public artwork nearby and notice different details together",
      "Choose a short route together based on shade rather than speed",
      "Look for a tiny natural pattern together from a safe path",
      "Sit outside and each invent a story about a cloud",
      "Compare what feels familiar and new on a shared walk",
      "Look for a building detail neither of you had noticed before",
      "Enjoy a short walk together without checking your phones",
      "Find a pleasant place to pause on the way home together",
      "Look for three kinds of green in a small outdoor area",
      "Take turns choosing something outdoors to observe closely",
      "Visit an accessible waterside viewpoint together and watch from a safe spot",
      "Walk around one familiar block and choose your favorite detail each",
      "Notice how the same breeze sounds in different trees together",
      "Find an interesting shadow outside and describe its shape to each other",
      "Share a short outdoor break between everyday activities",
      "Look for plants growing in unexpected little spaces together",
      "Observe a nearby garden from the path without disturbing it",
      "Find a place where the sky is framed by buildings together",
      "Compare your favorite parts of a familiar neighborhood view",
      "Take a gentle stroll together with no distance target",
      "Watch a short stretch of sunset together without looking directly at the sun",
      "Find a pleasing outdoor texture and each describe it differently",
      "Notice one thing on a walk that you would otherwise have missed",
      "Choose a nearby place you would like to revisit together"
    ]
  },
  {
    "prefix": "kind-company",
    "category": "Connect",
    "duration": "10 min",
    "icon": "♡",
    "company": "together",
    "texts": [
      "Tell someone a specific way they make ordinary days easier",
      "Offer to keep a friend company during a small chore",
      "Ask someone whether a short listening break would help",
      "Thank a friend for a quality you do not often mention",
      "Share a small task with someone so neither has to do it alone",
      "Invite someone to take a no-pressure break with you",
      "Offer a friend a choice between chatting and quiet company",
      "Help someone find a misplaced everyday item if they want assistance",
      "Leave a shared space a little nicer with someone",
      "Take turns naming something you appreciate about the other person's efforts",
      "Ask a friend what kind of encouragement feels useful today",
      "Offer to read something aloud for someone who would enjoy it",
      "Give someone your full attention for a short story they want to tell",
      "Share a spare useful item with someone who needs it",
      "Thank someone for a small kindness you still remember",
      "Make a comforting drink for someone with their preferences in mind",
      "Ask a friend whether they would enjoy a short distraction",
      "Offer to help carry something manageable if assistance is welcome",
      "Let someone choose the music for a shared break",
      "Tell a friend about a small thing they taught you",
      "Share an encouraging note with someone working on a personal project",
      "Ask someone what went a little easier than expected today",
      "Offer a friend a few minutes of company while they get started",
      "Choose one small shared responsibility to make easier together",
      "Tell someone what you admire about their creativity",
      "Thank a person who regularly helps behind the scenes",
      "Share a favorite low-effort comfort with someone who wants ideas",
      "Ask a friend which recent effort deserves a little celebration",
      "Offer to tidy one small shared area together",
      "Let someone know that a thoughtful gesture mattered to you",
      "Share a small success and invite someone to share theirs",
      "Ask a friend to tell you about something they are proud of",
      "Give someone time to finish speaking without rushing the conversation",
      "Make a tiny congratulatory drawing for someone you know",
      "Offer to explain a familiar skill if someone wants to learn",
      "Thank someone for making you feel included",
      "Invite a friend to choose an easy activity you can do together",
      "Ask someone whether they would prefer advice or a listening ear",
      "Share a practical tip only after asking if it would be useful",
      "Tell a friend a happy memory in which they played a part",
      "Offer to join someone for a task they find a little boring",
      "Make space for someone to share an interest you know little about",
      "Thank a friend for being honest in a kind way",
      "Ask someone what would make your shared space more comfortable",
      "Share the last word of a conversation by asking what they would add",
      "Offer a small favor with an easy way for the person to decline",
      "Send someone a personal note about something they do well",
      "Let a friend know you enjoyed spending ordinary time together",
      "Celebrate someone's progress without comparing it to anyone else's",
      "Ask someone to choose how you spend a short shared break",
      "End a conversation by naming one thing you enjoyed hearing"
    ]
  },
  {
    "prefix": "cozy-company",
    "category": "Slow down together",
    "duration": "15 min",
    "icon": "☾",
    "company": "together",
    "texts": [
      "Read separate books beside each other for a little while",
      "Share a quiet tea break without planning the rest of the day",
      "Sit together near a window and watch the weather",
      "Do separate small crafts in the same comfortable space",
      "Listen to gentle background music while quietly keeping each other company",
      "Share a blanket only if both of you are comfortable with it",
      "Take a short pause together before starting another activity",
      "Look through an illustrated book together at an unhurried pace",
      "Choose a comfortable place to sit and simply be together",
      "Make a little reading corner together using what you have",
      "Watch a short peaceful nature video together",
      "Sit together while each enjoys a favorite warm drink",
      "Fold a small stack of clean towels together slowly",
      "Arrange cushions together for a comfortable shared rest",
      "Spend a few minutes together without needing to keep talking",
      "Choose a familiar comforting story to read a page from together",
      "Sit in a shaded spot together and enjoy a quiet pause",
      "Do a simple jigsaw section together without trying to finish it",
      "Share a screen-free break after a busy stretch",
      "Look through a small album together and pause wherever you like",
      "Have a quiet snack together with no other activity",
      "Choose softer lighting together for a calm corner",
      "Sit together and listen to rain from indoors",
      "Read a short poem aloud to someone who would enjoy it",
      "Spend a little time together with a familiar pet that welcomes company",
      "Take turns reading short passages from a favorite book",
      "Enjoy a comfortable pause together after arriving somewhere",
      "Work on separate doodles at the same table",
      "Watch shadows change together on a nearby wall",
      "Choose a gentle documentary segment to watch together",
      "Set out a cozy place for an easy conversation together",
      "Share a few minutes of quiet after a long day",
      "Sort a small collection together and enjoy the details",
      "Listen to the end of a shared album track before moving on",
      "Make a low-effort plan together for a restful evening",
      "Choose a pleasant view and sit with it together",
      "Have a tiny indoor picnic on a clear comfortable surface",
      "Take a break together without discussing your to-do lists",
      "Browse a favorite picture book together for the illustrations alone",
      "Share a calm moment before saying goodbye",
      "Do a simple coloring page together at your own pace",
      "Arrange a little snack tray together for a quiet break",
      "Look at an old map together and let your eyes wander",
      "Spend a few minutes together with phones out of reach",
      "Share a comfortable silence without trying to fill it",
      "Choose one soothing sound to listen to together",
      "Enjoy a slow drink together while looking outside",
      "Create a small pause between shared errands",
      "Sit together somewhere familiar and notice how it feels today",
      "Agree on a gentle stopping point for a shared activity",
      "Let a shared break be complete without taking a photo of it"
    ]
  },
  {
    "prefix": "learn-together",
    "category": "Discover together",
    "duration": "15 min",
    "icon": "✦",
    "company": "together",
    "texts": [
      "Look up an unfamiliar animal together and each choose a favorite fact",
      "Teach each other one simple skill you already know",
      "Explore a museum's online artwork together and compare details",
      "Learn a short greeting in a language new to both of you",
      "Watch a brief craft demonstration together and discuss the process",
      "Look up the history of a place you both know",
      "Choose an unfamiliar instrument and listen to it together",
      "Read about an everyday invention together",
      "Learn a simple paper fold together from instructions",
      "Explore an old photograph together and notice different clues",
      "Find out how a favorite shared snack is made",
      "Look up a plant you both see regularly",
      "Read a short science explanation together and summarize it in plain words",
      "Explore a historical map of your area together",
      "Learn the name of a common architectural detail together",
      "Choose a short article about a shared interest and compare takeaways",
      "Ask each other to explain a hobby in beginner-friendly terms",
      "Look up the meaning of a word neither of you uses often",
      "Learn how a familiar toy works together",
      "Explore a public library's digital collection together",
      "Watch a short animation about a natural process together",
      "Look up the origin of a familiar game together",
      "Choose an artwork and each invent a title before reading its real one",
      "Learn about a traditional musical instrument together",
      "Read about a surprising animal friendship together",
      "Explore the design of an everyday object you both use",
      "Find out why a local place has an unusual name",
      "Learn a simple knot together using spare string",
      "Watch a short demonstration of a repair skill together",
      "Look up an unusual building together and discuss its shape",
      "Read about the making of a favorite animated film together",
      "Explore a new-to-you style of illustration together",
      "Learn about a small invention that changed daily life",
      "Compare two maps of the same place from different times",
      "Find out how one familiar fabric is produced together",
      "Read about a community garden project together",
      "Learn the name of a bird call you have both heard",
      "Explore a short account of a scientific discovery together",
      "Choose an unfamiliar craft material and learn what people make with it",
      "Read about the history of a common writing tool together",
      "Learn a simple rhythm pattern together",
      "Look up a constellation and trace its shape on paper together",
      "Explore an interesting bridge together through photographs",
      "Read about a traditional game and discuss how it works",
      "Learn something about a region connected to a shared favorite food",
      "Watch a short behind-the-scenes clip about miniature model making",
      "Compare what each of you notices in a historical poster",
      "Read about an artist's everyday working routine together",
      "Look up how a familiar kitchen tool was invented",
      "Share one useful thing each of you learned recently",
      "Choose one curiosity to explore together without needing to master it"
    ]
  },
  {
    "prefix": "shared-table",
    "category": "Little joy together",
    "duration": "15 min",
    "icon": "◒",
    "company": "together",
    "texts": [
      "Arrange a simple snack plate together using foods you both enjoy",
      "Choose a drink each and have a tiny café break at home",
      "Share stories about favorite breakfasts while enjoying a snack",
      "Make a picnic plan together using food already available",
      "Compare the textures of two familiar foods you both choose",
      "Create playful names for the snacks on your table",
      "Put together a colorful plate with ingredients you already have",
      "Share a familiar snack and talk about where you first tried it",
      "Set a small table together as if welcoming a special guest",
      "Take turns choosing a comforting drink for yourselves",
      "Make a simple sandwich together with familiar ingredients",
      "Arrange fruit into a cheerful pattern together before eating",
      "Share a snack break where nobody needs to host perfectly",
      "Compare your favorite ways to enjoy a familiar ingredient",
      "Write a tiny menu together for an imaginary weekend brunch",
      "Choose a familiar recipe together to try another time",
      "Prepare a cold drink together with ingredients you both like",
      "Share a meal memory connected to a place you both know",
      "Make a little tasting plate of familiar foods with ingredients everyone knows",
      "Decorate a snack plate together with a paper place card",
      "Share a quiet breakfast moment without screens",
      "Take turns describing a favorite food without naming it",
      "Plan a simple potluck idea together without making commitments",
      "Make an easy toast topping together from familiar ingredients",
      "Enjoy a warm drink together and compare your favorite mugs",
      "Arrange a small indoor picnic together on a comfortable surface",
      "Share a food tradition you remember from childhood",
      "Create a pretend café name for your shared snack break",
      "Put together a simple yogurt or fruit bowl with chosen toppings",
      "Talk about a meal you would enjoy making together someday",
      "Set out a shared snack and let everyone choose their own portion",
      "Compare the shapes of two familiar types of pasta before cooking another day",
      "Make a no-cook snack together using what is already in the kitchen",
      "Share a story about a pleasant surprise at a restaurant or café",
      "Decorate folded napkins together for an ordinary meal",
      "Choose a favorite familiar treat to enjoy together slowly",
      "Create a list together of easy meals you both like",
      "Bring your own drinks to a short doorstep chat with someone you know",
      "Arrange familiar snack ingredients into a little face together",
      "Share the preparation of a simple lunch without rushing",
      "Invent a fictional restaurant together around one favorite ingredient",
      "Compare how you each first learned to make a simple food",
      "Prepare two different familiar drinks and enjoy them side by side",
      "Choose a recipe picture together for its colors and presentation",
      "Turn an ordinary snack break into a tiny celebration together",
      "Make a simple fruit salad together with foods everyone can enjoy",
      "Share a kitchen memory connected to someone you appreciate",
      "Set out cups together for a short afternoon pause",
      "Enjoy the same familiar snack in different ways and compare preferences",
      "Write a playful review together of your homemade snack arrangement",
      "Finish a shared food break by putting the dishes away together"
    ]
  },
  {
    "prefix": "far-apart",
    "category": "Connect from afar",
    "duration": "10 min",
    "icon": "♡",
    "company": "together",
    "texts": [
      "Invite a friend to a short call while you each enjoy a drink",
      "Exchange photos of a small cheerful detail without sharing private information",
      "Send a friend a voice note describing a pleasant moment",
      "Draw the same simple object separately and compare pictures",
      "Play a quick word-association game over messages",
      "Choose a short poem to read at the same time from different places",
      "Send a friend a tiny drawing made just for them",
      "Compare the colors of the sky where you each are",
      "Trade a photo of a favorite everyday object and its story",
      "Listen to the same song separately and share what you noticed",
      "Start a two-person story in messages, one sentence each",
      "Invite someone to a short virtual craft break",
      "Exchange a simple riddle about an object near you",
      "Share a picture of a doodle and invite a friend to name it",
      "Ask a distant friend which ordinary sound they can hear right now",
      "Choose a theme for a tiny photo exchange with someone you know",
      "Send a friend a recommendation with a personal reason you chose it",
      "Take a short call while each person sits somewhere comfortable",
      "Trade descriptions of your ideal afternoon without comparing productivity",
      "Make a collaborative playlist with one song each to begin",
      "Exchange a small local discovery with a distant friend",
      "Read separate books during a short quiet call if you both enjoy that",
      "Send a friend a three-word clue about something that made you smile",
      "Compare a familiar recipe's name where each of you grew up",
      "Invite a friend to send a voice note about a hobby they enjoy",
      "Draw an imaginary animal together through alternating messages",
      "Share a short public museum link and choose a favorite artwork each",
      "Exchange tiny lists of things that made the week gentler",
      "Ask a friend to choose a color for your next doodle",
      "Send someone a photo of nature without including identifiable people",
      "Have a short call devoted to a shared interest rather than updates",
      "Trade a gentle joke with someone who enjoys your humor",
      "Choose a familiar film scene to discuss with a friend by message",
      "Send a friend a description of a place that reminded you of them",
      "Compare the first books you remember choosing for yourselves",
      "Invite someone to a five-minute screen-free phone chat",
      "Share a small creative attempt without asking for a rating",
      "Trade ideas for an imaginary trip you would take together",
      "Ask a friend to send the title of a comforting song",
      "Make a tiny digital postcard for someone you miss",
      "Exchange a photo of a handmade object you each appreciate",
      "Play a short guessing game through voice notes",
      "Choose one word each and build a little story from them",
      "Ask a friend about a pleasant detail in their current surroundings",
      "Send someone a short note about a memory you share",
      "Look at the same public artwork online during a short call",
      "Exchange a tiny challenge to notice something lovely nearby",
      "Invite a friend to share a no-pressure progress update on a hobby",
      "Trade pictures of paper creations made from scraps",
      "Share a simple plan for when you next get to meet",
      "End a short remote catch-up with something you are glad you shared"
    ]
  }
];

export const expandedTasks = groups.flatMap(({prefix, category, duration, icon, company, texts}) =>
  texts.map((text, index) => ({
    id: `${prefix}-${String(index + 1).padStart(3, '0')}`,
    text, category, duration, icon, company,
  })),
);
