// Curated additions. Stable category-and-position IDs preserve diary references.
// Append within a group; do not reorder existing items when editing this collection.
const groups = [
  ['notice', 'Be present', '3 min', '❋', [
    'Find three different shades of the same color around you',
    'Listen for the quietest sound you can hear',
    'Notice the feeling of your feet resting on the floor',
    'Study the shape and texture of an everyday object',
    'Watch the light move across a wall',
    'Notice three things in your room you usually overlook',
    'Listen to the sounds outside for one minute',
    'Look closely at the pattern on a leaf',
    'Notice where you feel supported by your chair',
    'Watch the steam rise from a warm drink',
    'Find something round, something soft, and something bright',
    'Notice the different textures of your clothes',
    'Look at a familiar room from a different seat',
    'Watch a shadow and trace its outline with your eyes',
    'Pay attention to the first bite of your next snack',
    'Listen to a whole song without doing anything else',
    'Notice the temperature of the air on your skin',
    'Study the details of a favorite photograph',
    'Find a small sign of the current season',
    'Notice one ordinary thing that makes your life easier',
  ]],
  ['creative', 'Create', '10 min', '✎', [
    'Draw a tiny imaginary creature and give it a name',
    'Write a four-line poem about your day',
    'Make a paper bookmark from a scrap of paper',
    'Draw your favorite mug without lifting your pen',
    'Invent a name for the color of the sky today',
    'Write a six-word story',
    'Make a little collage from paper you already have',
    'Draw a map of an imaginary island',
    'Write an alternate ending to a familiar story',
    'Create a repeating pattern of dots and lines',
    'Fold a paper fan',
    'Draw a postcard of somewhere you would like to visit',
    'Make up a silly rhyme about an object nearby',
    'Arrange a few everyday objects into a tiny sculpture',
    'Sketch the view from your seat',
    'Design a pretend book cover for your day',
    'Write a short scene set in a cozy place',
    'Draw three different expressions on little cartoon faces',
    'Make a list of playful names for an imaginary café',
    'Fill a small piece of paper with your favorite color',
  ]],
  ['connection', 'Connect', '5 min', '♡', [
    'Thank someone for a specific little thing they did',
    'Send a friend a song that reminds you of them',
    'Ask someone you trust about the best part of their day',
    'Share a funny, gentle memory with a friend',
    'Leave a kind note for someone you live with',
    'Send a simple hello to someone you have been meaning to contact',
    'Give someone a sincere compliment about their effort',
    'Invite a friend to take a short walk another day',
    'Ask a friend what they have enjoyed reading lately',
    'Tell someone one thing you appreciate about them',
    'Send a photo of something lovely to a friend',
    'Reply to a friendly message you have wanted to answer',
    'Ask someone to recommend a favorite song',
    'Write a postcard or letter, even if you do not send it',
    'Share a small piece of good news with someone you trust',
    'Give a familiar pet some attention if it welcomes it',
    'Plan a low-key catch-up with someone whose company you enjoy',
    'Leave an encouraging comment on a friend’s creative work',
    'Ask someone about a hobby they love',
    'Tell a friend you are glad they are in your life',
  ]],
  ['space', 'Make room', '5 min', '✦', [
    'Put five things back where they belong',
    'Clear just enough desk space for your next activity',
    'Wipe down your favorite mug',
    'Straighten one small shelf',
    'Fluff a cushion or fold a blanket',
    'Make a comfortable spot for reading',
    'Put a fresh towel within reach',
    'Gather loose pens into one place',
    'Clear a safe path through your room',
    'Put away one item of clean clothing',
    'Choose a small object you love and give it a visible spot',
    'Sort one small stack of papers',
    'Neaten the area beside your bed',
    'Refill the soap dispenser if it needs it',
    'Set out the things you need for a peaceful morning',
    'Make your bed as simply as you like',
    'Brush crumbs off your table',
    'Organize one pocket of your bag',
    'Put your keys in an easy-to-find place',
    'Move a lamp to make your resting spot more comfortable',
  ]],
  ['reflection', 'Reflect', '5 min', '▤', [
    'Describe your current mood using a weather word',
    'Write about a small thing that surprised you today',
    'Name something you would like more time for',
    'Write one sentence about what you need right now',
    'Remember a time you learned something at your own pace',
    'List three qualities you value in a friend',
    'Write down a question you are curious about',
    'Describe a place where you feel at ease',
    'Name a small choice you are glad you made',
    'Write a note to your future self for a tiring day',
    'List three ordinary comforts you enjoy',
    'Recall a kind thing someone once said to you',
    'Write down something you are allowed to leave unfinished today',
    'Describe a small moment you would like to remember',
    'Name one thing you have learned about yourself recently',
    'Write about a favorite childhood pastime',
    'List a few things that help you feel at home',
    'Choose one word you would like to guide the rest of your day',
    'Recall something that felt difficult once and feels easier now',
    'Write down what a restful evening could look like for you',
  ]],
  ['joy', 'Little joy', '5 min', '✳', [
    'Listen to the theme song of a show you used to love',
    'Look through a favorite illustrated book',
    'Choose a cheerful photo for your phone wallpaper',
    'Read a short comic strip',
    'Wear a favorite accessory just for yourself',
    'Make a tiny playlist for a cozy afternoon',
    'Watch one short clip that reliably makes you laugh',
    'Revisit a favorite passage from a book',
    'Enjoy the view from your favorite nearby window',
    'Arrange your snack nicely on a plate',
    'Browse a few pictures of an animal you love',
    'Listen to a song from a happy period of your life',
    'Try a simple word puzzle for fun',
    'Sing or hum a chorus you know by heart',
    'Look at the cover art of a favorite album',
    'Invent a tiny celebration for getting through today so far',
    'Pick a favorite scent you already own and enjoy it briefly',
    'Read a few lighthearted jokes',
    'Look through a small collection you enjoy',
    'Give today a playful title, like a chapter in a book',
  ]],
  ['outdoors', 'Fresh air', '10 min', '☀', [
    'Sit outside in a comfortable, shaded spot',
    'Listen for birds from a safe place nearby',
    'Take a short route past a tree you like',
    'Look for interesting patterns in tree bark',
    'Notice the colors of the buildings on your street',
    'Watch the breeze move leaves or grass',
    'Visit a nearby bench and pause for a moment',
    'Look for a flower without picking it',
    'Watch the sky change color near sunset from a safe spot',
    'Notice a detail on a familiar walking route that is new to you',
    'Step outside to check what the air feels like today',
    'Look at the shapes of nearby rooftops against the sky',
    'Listen to rain from a sheltered place',
    'Watch a small patch of nature without disturbing it',
    'Take a photo of an interesting shadow outdoors',
    'Look for three different leaf shapes',
    'Visit a nearby garden if one is accessible to you',
    'Notice a pleasant outdoor sound and stay with it briefly',
    'Pause beside a favorite local landmark',
    'Watch the evening sky from your doorway or window',
  ]],
  ['ease', 'Self kindness', '3 min', '♡', [
    'Adjust your chair or cushions until you feel supported',
    'Loosen an uncomfortable accessory or piece of clothing',
    'Put a soft blanket within reach',
    'Give yourself permission to do one thing more slowly',
    'Choose the easier version of one task on your list',
    'Put a glass of water beside your resting spot',
    'Rest your hands comfortably in your lap for a minute',
    'Relax your jaw and let your shoulders settle comfortably',
    'Lower the volume of something that feels too loud',
    'Adjust a bright light to a more comfortable level',
    'Make room in your schedule for a short break',
    'Say to yourself: I can take this one step at a time',
    'Put on a fresh pair of comfortable socks',
    'Wash your face with water at a comfortable temperature',
    'Apply a familiar hand cream if you enjoy using it',
    'Set a gentle stopping point for today’s work',
    'Let one nonessential chore wait until another day',
    'Choose a comfortable position and rest without a goal',
    'Notice a comparison you can set aside for today',
    'Write yourself the encouragement you would offer a friend',
  ]],
  ['curiosity', 'Get inspired', '10 min', '✦', [
    'Read a short poem by a writer you have not tried before',
    'Look up the meaning of a word you have wondered about',
    'Learn the name of a common plant in your area',
    'Explore one artwork in a museum’s online collection',
    'Listen to a song in a language you do not speak',
    'Read about how an everyday object is made',
    'Learn a friendly greeting in another language',
    'Look up the story behind a favorite song',
    'Find out one interesting fact about the moon',
    'Read a short biography of someone creative',
    'Browse a library catalog for one book you might enjoy',
    'Watch a short demonstration of a craft that interests you',
    'Learn the name of a bird you often see',
    'Read about a place you would like to visit someday',
    'Find a recipe you could make with familiar ingredients',
    'Look up the origin of a favorite expression',
    'Learn about one constellation',
    'Explore a style of music you rarely listen to',
    'Read an interview with an artist whose work you like',
    'Write down an idea you would enjoy exploring someday',
  ]],
  ['small-reset', 'Slow down', '5 min', '☾', [
    'Enjoy a drink while sitting down away from your desk',
    'Set your phone out of reach for one short break',
    'Read one page slowly instead of rushing through it',
    'Spend a few minutes doing only one thing',
    'Pause before starting the next item on your list',
    'Listen to a short recording of gentle nature sounds',
    'Let a cup of tea cool while you sit quietly',
    'Close a few browser tabs you no longer need',
    'Put your work materials aside at the end of a session',
    'Take a break from checking the time',
    'Leave your next few minutes deliberately unplanned',
    'Sit in a quiet spot without trying to be productive',
    'Look through a paper book instead of a screen for a while',
    'Savor a familiar piece of music with your eyes resting',
    'Take your next snack break without multitasking',
    'Pause a video and notice how you feel before continuing',
    'Put tomorrow’s first small task on paper, then leave it there',
    'Choose one thing to do at a comfortable pace',
    'Give yourself a few quiet minutes after a busy conversation',
    'Finish this moment before deciding what comes next',
  ]],
];

export const extraTasks = groups.flatMap(([prefix, category, duration, icon, texts]) =>
  texts.map((text, index) => ({
    id: `${prefix}-${String(index + 1).padStart(2, '0')}`,
    text,
    category,
    duration,
    icon,
  })),
);
